package com.bravetube.tv.data

import kotlinx.serialization.Serializable

/**
 * Wire models for the Piped API (https://docs.piped.video/docs/api-documentation/).
 * Every field is nullable / defaulted because public instances vary in what they return.
 */

@Serializable
data class StreamItem(
    val url: String? = null,
    val type: String? = null,
    val title: String? = null,
    val thumbnail: String? = null,
    val uploaderName: String? = null,
    val uploaderUrl: String? = null,
    val uploaderAvatar: String? = null,
    val uploadedDate: String? = null,
    val shortDescription: String? = null,
    val duration: Long = -1,
    val views: Long = -1,
    val uploaded: Long = -1,
    val uploaderVerified: Boolean = false,
    val isShort: Boolean = false,

    // channel-result fields
    val name: String? = null,
    val description: String? = null,
    val subscribers: Long = -1,
    val videos: Long = -1,
    val avatar: String? = null,
    val verified: Boolean = false,
) {
    val videoId: String?
        get() = url?.let { extractVideoId(it) }

    val channelId: String?
        get() = extractChannelId(url) ?: extractChannelId(uploaderUrl)

    val displayTitle: String get() = title ?: name.orEmpty()
    val displayThumb: String? get() = thumbnail ?: avatar
    val isChannel: Boolean get() = type == "channel"
    val isPlaylist: Boolean get() = type == "playlist"
    val isVideo: Boolean get() = !isChannel && !isPlaylist
}

@Serializable
data class SearchResponse(
    val items: List<StreamItem> = emptyList(),
    val nextpage: String? = null,
    val suggestion: String? = null,
    val corrected: Boolean = false,
)

@Serializable
data class PipedStream(
    val url: String? = null,
    val format: String? = null,
    val quality: String? = null,
    val mimeType: String? = null,
    val codec: String? = null,
    val videoOnly: Boolean = false,
    val bitrate: Long = 0,
    val width: Int = 0,
    val height: Int = 0,
    val fps: Int = 0,
    val contentLength: Long = -1,
    val audioTrackName: String? = null,
) {
    /** "1080p60" -> 1080, "144p" -> 144, "" -> 0 */
    val heightPx: Int
        get() = if (height > 0) height else quality?.substringBefore("p")?.toIntOrNull() ?: 0

    val label: String
        get() = quality ?: (if (heightPx > 0) "${heightPx}p" else "auto")
}

@Serializable
data class Subtitle(
    val url: String? = null,
    val mimeType: String? = null,
    val name: String? = null,
    val code: String? = null,
    val autoGenerated: Boolean = false,
)

@Serializable
data class VideoDetails(
    val title: String? = null,
    val description: String? = null,
    val uploadDate: String? = null,
    val uploader: String? = null,
    val uploaderUrl: String? = null,
    val uploaderAvatar: String? = null,
    val thumbnailUrl: String? = null,
    val hls: String? = null,
    val dash: String? = null,
    val lbryId: String? = null,
    val category: String? = null,
    val uploaderVerified: Boolean = false,
    val duration: Long = 0,
    val views: Long = -1,
    val likes: Long = -1,
    val dislikes: Long = -1,
    val subscriberCount: Long = -1,
    val livestream: Boolean = false,
    val audioStreams: List<PipedStream> = emptyList(),
    val videoStreams: List<PipedStream> = emptyList(),
    val relatedStreams: List<StreamItem> = emptyList(),
    val subtitles: List<Subtitle> = emptyList(),
) {
    val channelId: String? get() = extractChannelId(uploaderUrl)
}

@Serializable
data class ChannelDetails(
    val id: String? = null,
    val name: String? = null,
    val avatarUrl: String? = null,
    val bannerUrl: String? = null,
    val description: String? = null,
    val nextpage: String? = null,
    val subscriberCount: Long = -1,
    val verified: Boolean = false,
    val relatedStreams: List<StreamItem> = emptyList(),
)

/** A horizontal carousel on the home screen. */
data class Shelf(
    val id: String,
    val title: String,
    val items: List<StreamItem> = emptyList(),
    val loading: Boolean = true,
    val error: String? = null,
)

// ---------------------------------------------------------------- helpers

fun extractVideoId(url: String): String? {
    if (url.isBlank()) return null
    val marker = "v="
    val i = url.indexOf(marker)
    if (i >= 0) {
        val raw = url.substring(i + marker.length).substringBefore('&')
        if (raw.isNotBlank()) return raw
    }
    if (url.contains("youtu.be/")) {
        val raw = url.substringAfter("youtu.be/").substringBefore('?').substringBefore('&')
        if (raw.isNotBlank()) return raw
    }
    // bare id
    if (url.length == 11 && !url.contains('/')) return url
    return null
}

fun extractChannelId(url: String?): String? {
    if (url.isNullOrBlank()) return null
    val marker = "/channel/"
    val i = url.indexOf(marker)
    if (i < 0) return null
    val raw = url.substring(i + marker.length).substringBefore('?').substringBefore('/')
    return raw.takeIf { it.isNotBlank() }
}

fun formatViews(views: Long): String = when {
    views < 0 -> ""
    views >= 1_000_000_000 -> String.format("%.1fB views", views / 1_000_000_000.0)
    views >= 1_000_000 -> String.format("%.1fM views", views / 1_000_000.0)
    views >= 1_000 -> String.format("%.1fK views", views / 1_000.0)
    else -> "$views views"
}

fun formatSubs(subs: Long): String = when {
    subs < 0 -> ""
    subs >= 1_000_000 -> String.format("%.1fM subscribers", subs / 1_000_000.0)
    subs >= 1_000 -> String.format("%.1fK subscribers", subs / 1_000.0)
    else -> "$subs subscribers"
}

/** seconds -> 1:02:03 / 4:05 */
fun formatDuration(seconds: Long): String {
    if (seconds <= 0) return ""
    val h = seconds / 3600
    val m = (seconds % 3600) / 60
    val s = seconds % 60
    return if (h > 0) String.format("%d:%02d:%02d", h, m, s) else String.format("%d:%02d", m, s)
}

/** milliseconds -> 1:02:03 / 4:05, always renders (used by the player scrubber) */
fun formatPosition(ms: Long): String {
    val safe = if (ms < 0) 0 else ms / 1000
    val h = safe / 3600
    val m = (safe % 3600) / 60
    val s = safe % 60
    return if (h > 0) String.format("%d:%02d:%02d", h, m, s) else String.format("%d:%02d", m, s)
}
